### ISSUE TITLE
Add travis CI 

### ISSUE THREAD

**Issue by hortinstein** [hanwang/geobins#3]
Han, can you add this to your Travis CI and add the badge here?

**Comment by hanwang** [comment]
I actually don't have a Travis CI account, would you like to set it up on yours?

**Comment by hortinstein** [comment]
Just make one real quick, I can't since I don't own the repo.  You can sign
in with your github and just switch it on.  I already have the
configuration in the repo

**Comment by hanwang** [comment]
Hooked in.
